name: "Run tests for amd64 architecture"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: "Python 3.7"
            python-version: '3.7'
            toxenv: 'py37'
          - name: "Python 3.8"
            python-version: '3.8'
            toxenv: 'py38'
          - name: "Python 3.9"
            python-version: '3.9'
            toxenv: 'py39'
          - name: "Python 3.10"
            python-version: '3.10'
            toxenv: 'py310'
          - name: "Pypy 3.10"
            python-version: 'pypy-3.10'
            toxenv: 'pypy3'
          - name: "Python 3.11"
            python-version: '3.11'
            toxenv: 'py311'
#          - name: "Python 3.12"
#            python-version: '3.12'
#            toxenv: 'py312'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 'setuptools<58' --force-reinstall
          pip install 'tox<4' tox-gh-actions flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Tests with tox
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: |
          tox
      - name: Linting
        if: ${{ matrix.python-version==3.11 }}
        env:
          TOXENV: lint
        run: |
          tox
      - name: Run Codecov
        if: ${{ matrix.python-version==3.11 }}
        env:
          TOXENV: lint
        run: |
          pip install codecov
          codecov
      - name: Upload coverage to Codecov
        if: ${{ matrix.python-version==3.11 }}
        uses: codecov/codecov-action@v3
